// Contract-driven property tests for aprender kernels.
//
// Each module corresponds to a YAML kernel contract in
// provable-contracts/contracts/. Tests are generated by
// `pv probar --binding` and hand-tuned to call real aprender
// functions via proptest.
//
// Regenerate with:
//   cd ../provable-contracts && pv probar --binding \
//     contracts/<kernel>.yaml \
//     --binding contracts/aprender/binding.yaml

mod activation_contract;
mod adamw_contract;
mod arch_requirements_contract;
mod arima_contract;
mod attention_contract;
mod backend_dispatch_contract;
mod batchnorm_contract;
mod bayesian_contract;
mod calibration_contract;
mod classification_metrics_contract;
mod clustering_metrics_contract;
mod cma_es_contract;
mod conv1d_contract;
mod cross_entropy_contract;
mod decision_tree_contract;
mod drift_contract;
mod f16_conversion_contract;
mod flash_attention_contract;
mod format_parity_contract;
mod gated_delta_net_contract;
mod gbm_contract;
mod glm_contract;
mod gqa_contract;
mod graph_centrality_contract;
mod hybrid_layer_dispatch_contract;
mod ica_contract;
mod kernel_launch_budget_contract;
mod kmeans_contract;
mod kv_cache_equivalence_contract;
mod kv_cache_sizing_contract;
mod layernorm_contract;
mod lbfgs_contract;
mod linear_models_contract;
mod lora_algebra_contract;
mod loss_functions_contract;
mod matmul_contract;
mod model_config_algebra_contract;
mod naive_bayes_contract;
mod optimization_contract;
mod pagerank_contract;
mod pca_contract;
mod performance_grading_contract;
mod preprocessing_contract;
mod q4k_q6k_superblock_contract;
mod qk_norm_contract;
mod quantization_ordering_contract;
mod qwen35_shapes_contract;
mod random_forest_contract;
mod ranking_contract;
mod regression_metrics_contract;
mod rmsnorm_contract;
mod roofline_model_contract;
mod rope_contract;
mod sampling_algorithms_contract;
mod shannon_entropy_contract;
mod silu_contract;
mod softmax_contract;
mod ssm_contract;
mod svm_contract;
mod swiglu_contract;
mod tensor_inventory_contract;
mod tensor_shape_flow_contract;
mod validated_tensor_contract;
