// Contract-driven property tests for aprender kernels.
//
// Each module corresponds to a YAML kernel contract in
// provable-contracts/contracts/. Tests are generated by
// `pv probar --binding` and hand-tuned to call real aprender
// functions via proptest.
//
// Regenerate with:
//   cd ../provable-contracts && pv probar --binding \
//     contracts/<kernel>.yaml \
//     --binding contracts/aprender/binding.yaml

mod softmax_contract;
mod rmsnorm_contract;
mod activation_contract;
mod attention_contract;
mod matmul_contract;
mod rope_contract;
