// CONTRACT: swiglu-kernel-v1.yaml
// HASH: sha256:c9d0e1f2a3b45678
// Generated by: pv probar --binding
// DO NOT EDIT — regenerate with `pv probar --binding`

use proptest::prelude::*;

proptest! {
    /// Obligation: SwiGLU gate bounded in (0, x) (bound)
    /// Formal: 0 < SwiGLU(x, gate) < max(|x|, |gate|) * K
    #[test]
    #[ignore = "SwiGLU not exposed as public API"]
    fn prop_gate_bounded(
        _x in proptest::collection::vec(-10.0f32..10.0, 1..32usize)
    ) {
        // Blocked: SwiGLU is embedded in FFN layers, not exposed as standalone
    }

    /// Obligation: SwiGLU(0, gate) = 0 (invariant)
    /// Formal: SwiGLU(0, g) = 0 * SiLU(g) = 0
    #[test]
    #[ignore = "SwiGLU not exposed as public API"]
    fn prop_zero_input(
        _x in proptest::collection::vec(-10.0f32..10.0, 1..32usize)
    ) {
        // Blocked: no public SwiGLU function
    }

    /// Obligation: Output finite for finite inputs (invariant)
    /// Formal: finite(x) ∧ finite(gate) → finite(SwiGLU(x, gate))
    #[test]
    #[ignore = "SwiGLU not exposed as public API"]
    fn prop_finite_output(
        _x in proptest::collection::vec(-10.0f32..10.0, 1..32usize)
    ) {
        // Blocked: no public SwiGLU function
    }

    /// Obligation: SIMD matches scalar within ULP (equivalence)
    #[test]
    #[ignore = "SwiGLU not exposed as public API"]
    fn prop_simd_equivalence(
        _x in proptest::collection::vec(-10.0f32..10.0, 1..32usize)
    ) {
        // Blocked: no public SwiGLU function
    }
}
