comply:
  suppressions:
    - rules: ["CB-954"]
      files: ["contracts/**", "docs/roadmaps/**"]
      reason: "ML model config fields (eos_token, bos_token, embed_tokens) are not secrets — see paiml/paiml-mcp-agent-toolkit#203"
