comply:
  suppressions:
    - rules: ["CB-954"]
      files: ["contracts/**", "docs/roadmaps/**"]
      reason: "ML model config fields (eos_token, bos_token, embed_tokens) are not secrets — see paiml/paiml-mcp-agent-toolkit#203"
    - rules: ["CB-1000", "CB-1002", "CB-1007"]
      files: ["models", "models/**", "crates/apr-cli/models", "crates/apr-cli/models/**"]
      reason: "Local model cache directories are gitignored — model cards and tokenizers managed by upstream (HF Hub)"

rust-project-score:
  suppressions:
    - check: "unwrap_calls"
      reason: "unwrap() banned in production via .clippy.toml disallowed-methods. 180 count is tests/examples/book only (36 in src/ test modules, 0 in production). MUDA — false positive."
      exclude_paths: ["examples/**", "book/**", "src/**/tests.rs", "src/**/*_tests*.rs"]
