# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    project:
      default:
        target: 95%
        # CB-124: PMAT sovereign stack standard requires 95%
        threshold: 95%
    patch:
      default:
        target: 90%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  - "tests/**"
  - "benches/**"
  - "examples/**"
  - "crates/**"
  - "fuzz/**"
  - "scripts/**"
  - "golden_traces/**"
